manifest_version = 1

[package]
name = "example-rust-component"
version = "1.0.0"

wit-world-version = "0.3.0"

[package.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target"
output_path = "target/wasm32-wasip2/release/example_rust_component.wasm"
